travis:
  secure:
    BINSTAR_TOKEN: gM0jCEUANGt3sB1wEirTSa+kVuofVvUMaPvReumtDFWBuspJoC1cH7/9yGSfnqkd9adKBowRkDR0GDuLdaJIfm29NAUFfXk2WbJ/C3iGw01ZoavqGX7FnMtA1lcxphxIwzIlVzFTo2zkdjaupSA30tO0D1bob+4SzTn/3oIrqkx+KOJUn+SKuEPkpXPVhkbrC2Xdv5jKQyy4gX3EAD4ti6aNUubE9oHf/PNTwuwIl78VxpmNdlW6nll8xelIXvpUeB6WGTfiSKC35F2g96s/+/l+19YGk4cSIoBMAJ8lu1hDjKcicvYqTiy1gn8uZHvVEUXTX7qnDdTJ8iisdVv9DrGO94nkSCB+Hl1LHMXTFsUqs7TTsCNoLguGtxLw7eR93zQ5y/Y95YaxLGLuPo0h5CKLUaaj7rLth6go8f8Q7XjoiqadvOIf8MybxoLC4VnMKMM/ffW8RsjhWlNSSt8Rc4XKMXAa/hjjSOmRG/o4J3oiADMsDSXHbOxtYge20dtKEqCHuD3R62pKatVTY6MB+uGVJLzh+q1H8do9GRc/t5i5yr9dJc9EusWMpQTCW+VkSy63N8lTvG0OLnt+hKttqrZpuEWkVGQPnKctD15LDxpFuN+03+fV47qQns90eD13zQ/Q01Pg9G/YIDMT4GWeKmsN5hCcvJiCUKFkUNsJsKg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
